### ISSUE TITLE
テーマカラーの変更

### ISSUE THREAD

**Issue by 0505Keitan** [stop-covid19-kyoto/covid19-kyoto#18]
## 起こっている問題 / The Problem
- 岡山県の色になっている

## スクリーンショット / Screenshot

<img width="1409" alt="image" src="https://user-images.githubusercontent.com/24855244/76847882-1d051480-6886-11ea-90d3-35ab4d345a9c.png">

## 期待する見せ方・挙動 / Expected Behavior
- 京都色に変更

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by fujiwaraizuho** [comment]
京都色…🤔

**Comment by 0505Keitan** [comment]
@maconaco さんがやってた記憶

**Comment by 0505Keitan** [comment]
臙脂色 #9B003F ？
葡萄茶 #640125 ？
