### ISSUE TITLE
感染予防と相談窓口のリンク

### ISSUE THREAD

**Issue by 0505Keitan** [stop-covid19-kyoto/covid19-kyoto#26]
## 起こっている問題 / The Problem
- 感染予防と相談窓口のリンクが岡山県のものになっている

## 期待する見せ方・挙動 / Expected Behavior
- リンク先を京都府のものにする

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by 0505Keitan** [comment]
https://www.pref.kyoto.jp/kentai/news/novelcoronavirus.html#C
相談窓口はこれっぽい

**Comment by Genbuchan** [comment]
https://www.pref.kyoto.jp/kentai/news/novelcoronavirus.html#A
感染予防はこれ

**Comment by 0505Keitan** [comment]
2個ある場合どうしようか

**Comment by Genbuchan** [comment]
そのままにした方が、ページ間の遷移のことを考えると使いやすいと思う〜。
