### ISSUE TITLE
ページの URL が分からない

### ISSUE THREAD

**Issue by OldBigBuddha** [stop-covid19-kyoto/covid19-kyoto#58]
## 改善詳細 / Details of Improvement
ページの URL(https://stop-covid19-kyoto.netlify.com/) が分からなくなるのでリポの概要か README に貼っていおいて欲しい。

## 期待する見せ方・挙動 / Expected behavior
- README の上の方に URL を掲示する
- リポジトリの概要に URL を掲示する

おまけ
- Organization の URL として設定するのも良いかも

**Comment by f0reachARR** [comment]
CONTRIBUING.mdへの反映も追加

**Comment by 0505Keitan** [comment]
家帰り次第わたしやる
